### ISSUE TITLE
Duplicate rows in message.pot

### ISSUE THREAD

**Issue by Demian101** [google/mdbook-i18n-helpers#101]
when I run 
```bash
# gen message.po
MDBOOK_OUTPUT='{"xgettext": {"pot-file": "messages.pot"}}' \
  mdbook build -d po
```

there are so many duplicate rows, dont know why
<img width="873" alt="image" src="https://github.com/google/mdbook-i18n-helpers/assets/33189338/d69b8693-51a3-444a-96f4-4923f015e4ad">

<img width="706" alt="image" src="https://github.com/google/mdbook-i18n-helpers/assets/33189338/dc071755-0276-4cdf-af85-e05c5f2fd16c">

**Comment by mgeisler** [comment]
Alternatively (and probably more efficiently), we could handle this after all messages have been added just before this line:

https://github.com/google/mdbook-i18n-helpers/blob/941a188219c5b0492850ad54ea41303dcee49c82/i18n-helpers/src/bin/mdbook-xgettext.rs#L103

We could then also move the `textwrap::refill` call to that location.

**Comment by Demian101** [comment]
In some cases she may not be harmless lol 

<img width="869" alt="image" src="https://github.com/google/mdbook-i18n-helpers/assets/33189338/7926f4aa-c0c3-47bd-9b12-bd8efe191f2e">


<img width="618" alt="image" src="https://github.com/google/mdbook-i18n-helpers/assets/33189338/aac9b66a-89c7-4b4b-8311-51a43a239483">

So , i try to replace all `msgid "" msgstr ""`  to  `""`

**Comment by mgeisler** [comment]
Oh, thanks for pointing that out! You've run into #64...

**Comment by Demian101** [comment]
COOL！Thanks for your patience~   OK, Maybe it is because I used `cloud-tranlate` to gen the `en.po` .. 

**I aslo get another question maybe I should ask in the `cloud-tranlate` repo :**  

when I finished use `cloud-tranlate` repo  to translate and ran :
```bash
msgmerge --update po/en.po po/messages.pot
```
<img width="785" alt="image" src="https://github.com/google/mdbook-i18n-helpers/assets/33189338/520a7665-58f0-4379-b4c7-854cf1e6d14f">

<img width="719" alt="image" src="https://github.com/google/mdbook-i18n-helpers/assets/33189338/a1798330-ee60-446e-85a5-960a4986ce54">

**Comment by mgeisler** [comment]
Having duplicate messages (such as `"A"`) should be fine. The problem of adding empty messages (`""`) was fixed with #111.

I'm about to make a 0.3 release which has the fix above. Please open a new issue if you run into problem with this release.

**Comment by Demian101** [comment]
GREAT work! 
can't wait for the next version ~ 🤣

**Comment by mgeisler** [comment]
It has been released now! Please `cargo install mdbook-i18n-helpers` to get it! :smile:
