### ISSUE TITLE
Deduplicate repeated sources

### ISSUE THREAD

**Issue by mgeisler** [google/mdbook-i18n-helpers#154]
With #145 merged, we can now end up in a situation where a message has the same source repeated multiple times:

```gettext
#: src/SUMMARY.md:10 src/SUMMARY.md:10 src/SUMMARY.md:70 src/SUMMARY.md:90
msgid "Welcome"
msgstr "Te damos la bienvenida"
```

We should add logic to remove the duplicates in this case. The situation becomes even worse when the line numbers are removed completely (when granularity is set to `0`).

**Comment by zachcmadsen** [comment]
Hey @mgeisler, I'm interested in taking this. Based on #145, it looks like we'd need to handle duplicates whenever we call `add_message` in `create_catalog`. Am I on the right track?

**Comment by mgeisler** [comment]
Hi @zachcmadsen, thanks for taking this on! I think you're definitely on the right track!

**Comment by mgeisler** [comment]
I just created #171, which is related to this (but can be fixed independently).
