### ISSUE TITLE
codecov-action upgrade broke coverage reports

### ISSUE THREAD

**Issue by kdarkhan** [google/mdbook-i18n-helpers#173]
Coverage reports started failing after [upgrade from v3 to v4](https://github.com/google/mdbook-i18n-helpers/pull/169).

Example failure [here](https://github.com/google/mdbook-i18n-helpers/actions/runs/7804318002/job/21286005311)

Error message

```
==> Running version v0.4.6
==> Running command '/home/runner/work/_actions/codecov/codecov-action/v4/dist/codecov create-commit'
/home/runner/work/_actions/codecov/codecov-action/v4/dist/codecov create-commit -C 4a213d1e5bb64fed6de71036439f53d1c796564e --pr 155 -Z
info - 2024-02-06 18:22:00,803 -- ci service found: github-actions
warning - 2024-02-06 18:22:00,806 -- No config file could be found. Ignoring config.
info - 2024-02-06 18:22:00,951 -- Process Commit creating complete
error - 2024-02-06 18:22:00,951 -- Commit creating failed: ["Service not found: none"]
Traceback (most recent call last):
  File "codecov_cli/main.py", line 81, in <module>
  File "codecov_cli/main.py", line 77, in run
  File "click/core.py", line 1157, in __call__
  File "click/core.py", line 1078, in main
  File "click/core.py", line 1688, in invoke
  File "click/core.py", line 1434, in invoke
  File "click/core.py", line 783, in invoke
  File "click/decorators.py", line 33, in new_func
  File "codecov_cli/commands/commit.py", line 64, in create_commit
  File "codecov_cli/services/commit/__init__.py", line 39, in create_commit_logic
  File "codecov_cli/helpers/request.py", line 133, in log_warnings_and_errors_if_any
NameError: name 'exit' is not defined
[1739] Failed to execute script 'main' due to unhandled exception!
Error: Codecov: Failed to properly create commit: The process '/home/runner/work/_actions/codecov/codecov-action/v4/dist/codecov' failed with exit code 1
```

**Comment by mgeisler** [comment]
Hey @kdarkhan, I would suggest moving to the simplest setup: only generate covera reports after merges. That should work fine: it will allow us to use the privileged trigger from the `main` branch.

We will still get the history of coverage over time on `main` and we can then look at this to determine where we have big holes in our test coverage.

**Comment by kdarkhan** [comment]
@mgeisler, that can be done and it will simplify commit/PR detection logic I defined in the pipelines.

It will probably not resolve this specific issue as the bug is in the new version of codecov action. v3 version works pretty stable and v4 should be fixed eventually since there are many complaints from users on the breakage.

Removing PR comments can be done if you think they are distracting but not because of this upgrade failure.

**Comment by mgeisler** [comment]
> Removing PR comments/analysis can be done if you think they are distracting but not because of this upgrade failure.

Ah, I see! Then I think we should just keep things the way they are now. As you say, the issue will probably be fixed eventually.
