### ISSUE TITLE
Add github-actions check for validating Cargo.lock is up to date

### ISSUE THREAD

**Issue by kdarkhan** [google/mdbook-i18n-helpers#220]
More background in https://github.com/google/mdbook-i18n-helpers/pull/216#issuecomment-2255799969

**Comment by mgeisler** [comment]
My own favorite way of fixing this is to automate the releases :smile: 

I've done that for my own _library_ crates using https://github.com/mgeisler/rust-release-gh-action. It is used here, as an example: [`prepare-release.yml`](https://github.com/mgeisler/version-sync/blob/master/.github/workflows/prepare-release.yml), [`publish-crate.yml`](https://github.com/mgeisler/version-sync/blob/master/.github/workflows/publish-crate.yml).

The code doesn't know anything about workspaces, unfortunately, but I would of course like to see it gain that support.
