### ISSUE TITLE
HTML tag abbr seems to confuse the parser

### ISSUE THREAD

**Issue by HidenoriKobayashi** [google/mdbook-i18n-helpers#97]
I'm redirected to here from https://github.com/google/comprehensive-rust/issues/1284.

The source:
https://github.com/google/comprehensive-rust/blob/a38a33c8fba58678d0a9127d9644242bce41ed94/src/bare-metal/microcontrollers/probe-rs.md

The po file (bit outdated but updating it does not resolve the issue):
https://github.com/google/comprehensive-rust/blob/a38a33c8fba58678d0a9127d9644242bce41ed94/po/ja.po#L13420

Now, if I make this change (just for testing purpose)
```
diff --git a/po/ja.po b/po/ja.po
index b2baaf215743..2a9eb0c872d4 100644
--- a/po/ja.po
+++ b/po/ja.po
@@ -13418,7 +13418,7 @@ msgstr ""
 
 #: src/bare-metal/microcontrollers/probe-rs.md:10
 msgid "`cargo-embed` is a cargo subcommand to build and flash binaries, log "
-msgstr ""
+msgstr "`cargo-embed`"
 
 #: src/bare-metal/microcontrollers/probe-rs.md:11
 msgid "RTT"
```

I get a result like this:
![localhost_3000_bare-metal_microcontrollers_probe-rs html](https://github.com/google/mdbook-i18n-helpers/assets/17474478/124b815d-ca61-4332-be28-996495d7d56e)

The strange thing about this is that string `cargo-embed` got merged into the last item in the list.

**Comment by mgeisler** [comment]
I think what we see here is demonstrated by this test:

https://github.com/google/mdbook-i18n-helpers/blob/main/i18n-helpers/src/lib.rs#L748-L752

**Comment by mgeisler** [comment]
Further investigation shows that `extract_events(" BAZ", state)` give a `Text(Borrowed("BAZ"))` back! It should really give `" BAZ"` back so this seems to be where the space is lost.

**Comment by mgeisler** [comment]
This is actually fair: Markdown does not distinguish between a line of text starting with `"  foo"` vs `"foo"`. So when we extract the events, we lose the leading whitespace.

I'm not entirely sure where where we should account for this, but perhaps `extract_events` could add it back in? Or perhaps the caller should account for being in an inline context and then add it? Note that we have a `pulldown_cmark_to_cmark::State` object available and it knows that `last_was_html`... so that might be helpful here?

**Comment by mgeisler** [comment]
So I think these two tests should work:

```diff
diff --git a/i18n-helpers/src/bin/mdbook-gettext.rs b/i18n-helpers/src/bin/mdbook-gettext.rs
index b686be4..291bb2c 100644
--- a/i18n-helpers/src/bin/mdbook-gettext.rs
+++ b/i18n-helpers/src/bin/mdbook-gettext.rs
@@ -233,6 +233,15 @@ mod tests {
         );
     }
 
+    #[test]
+    fn test_translate_html() {
+        let catalog = create_catalog(&[("foo ", "FOO "), ("bar", "BAR"), (" baz", " BAZ")]);
+        assert_eq!(
+            translate("foo <b>bar</b> baz", &catalog),
+            "FOO <b>BAR</b> BAZ"
+        );
+    }
+
     #[test]
     fn test_translate_table() {
         let catalog = create_catalog(&[
diff --git a/i18n-helpers/src/lib.rs b/i18n-helpers/src/lib.rs
index 3bf2a5f..484d348 100644
--- a/i18n-helpers/src/lib.rs
+++ b/i18n-helpers/src/lib.rs
@@ -590,6 +590,30 @@ mod tests {
         assert_eq!(extract_events("", None), vec![]);
     }
 
+    #[test]
+    fn extract_events_leading_whitespace() {
+        assert_eq!(
+            extract_events("  foo", None),
+            vec![
+                (1, Start(Paragraph)),
+                (1, Text("  foo".into())),
+                (1, End(Paragraph)),
+            ]
+        );
+    }
+
+    #[test]
+    fn extract_events_trailing_whitespace() {
+        assert_eq!(
+            extract_events("foo  ", None),
+            vec![
+                (1, Start(Paragraph)),
+                (1, Text("foo  ".into())),
+                (1, End(Paragraph)),
+            ]
+        );
+    }
+
     #[test]
     fn extract_events_paragraph() {
         assert_eq!(
```

**Comment by mgeisler** [comment]
@kdarkhan, the problem here is about how we lose a `' '` when the Markdown AST is a mix of `Text` and `Html` nodes. I believe #125 is related: it's about how breaking apart the text on HTML elements causes problems. I think we could solve both problems if we would let `Text` and `Html` nodes be grouped together.

**Comment by kdarkhan** [comment]
I believe this should be resolved now with https://github.com/google/mdbook-i18n-helpers/pull/198 merged.
